### ISSUE TITLE
Roadmap to beta version

### ISSUE THREAD

**Issue by asg017** [asg017/dataflow#1]
I intend to "release" a `v0.1.0` sometime soon! `dataflow` already does most of what I want to do, but there still some cleaning up/error handling I want to include before I make an announcement notebook about it. At the same time, I don't wanna spend a long time building *everything*, `v1` will be looong down the road. 

Keeping TODOs here for ease/publicity, but please file bugs/problem in a separate issue and I'll merge here!

## Notebook editing

- [x] Error notification on parsing error
- [x] "Status bar" at bottom, show websocket connection status
- [x] Reconnect when websocket closes

## Compiling 

- [x] Support compiling notebooks with local `.ojs` imports
- [x] Support compiling notebooks with FileAttachments
- [x] Throw error when compiling a notebook that use Secrets
- [x] feature: compiler to directory

## For later
- [ ] Friendly messaging for syntax errors: e.g. `const x =4` , `window\n\n width`
- [x] Support compiling notebooks with custom stdlibs
- [ ] feature: inject styling, other JS into `<head>` of a `index.html`
- [ ] feature: customizable observable, i.e. "only render this one cell"
- [ ] `dataflow.startServer(port)`
- [ ] `dataflow.compile(source)`

**Comment by asg017** [comment]
Closing in favor of github's milestones, [Beta](https://github.com/asg017/dataflow/milestone/1) and [v1](https://github.com/asg017/dataflow/milestone/2)

**Comment by asg017** [comment]
using for pics

https://user-images.githubusercontent.com/15178711/118152924-23c7e280-b3ca-11eb-9862-8059087039b6.mp4
